import React from 'react'

const Index = () => {
    return (
        <div>
                      <div className="container my-5">
                <h1>Privacy</h1>
            <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                <br /> <br /> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
              <br /> <br />  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                <br /> <br /> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                <br /> <br />Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                <br /> <br /> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                <br /> <br /> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                <br /> <br /> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum nam incidunt pariatur deserunt adipisci architecto eveniet repudiandae rerum, porro vel quos! Quasi quas labore suscipit sint, facere consectetur dolorum fuga.

            </p>
        </div>
        </div>
    )
}

export default Index
